/**
 * @fileoverview gRPC-Web generated client stub for example.forum_rendering.proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: forum.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.example = {};
proto.example.forum_rendering = {};
proto.example.forum_rendering.proto = require('./forum_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.example.forum_rendering.proto.ForumRendererClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.example.forum_rendering.proto.ForumRendererPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.example.forum_rendering.proto.EmptyRequest,
 *   !proto.example.forum_rendering.proto.HTMLResponse>}
 */
const methodDescriptor_ForumRenderer_GetHomePage = new grpc.web.MethodDescriptor(
  '/example.forum_rendering.proto.ForumRenderer/GetHomePage',
  grpc.web.MethodType.UNARY,
  proto.example.forum_rendering.proto.EmptyRequest,
  proto.example.forum_rendering.proto.HTMLResponse,
  /**
   * @param {!proto.example.forum_rendering.proto.EmptyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.example.forum_rendering.proto.HTMLResponse.deserializeBinary
);


/**
 * @param {!proto.example.forum_rendering.proto.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.example.forum_rendering.proto.HTMLResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.example.forum_rendering.proto.HTMLResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.example.forum_rendering.proto.ForumRendererClient.prototype.getHomePage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/example.forum_rendering.proto.ForumRenderer/GetHomePage',
      request,
      metadata || {},
      methodDescriptor_ForumRenderer_GetHomePage,
      callback);
};


/**
 * @param {!proto.example.forum_rendering.proto.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.example.forum_rendering.proto.HTMLResponse>}
 *     Promise that resolves to the response
 */
proto.example.forum_rendering.proto.ForumRendererPromiseClient.prototype.getHomePage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/example.forum_rendering.proto.ForumRenderer/GetHomePage',
      request,
      metadata || {},
      methodDescriptor_ForumRenderer_GetHomePage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.example.forum_rendering.proto.EmptyRequest,
 *   !proto.example.forum_rendering.proto.HTMLResponse>}
 */
const methodDescriptor_ForumRenderer_GetNewPostPage = new grpc.web.MethodDescriptor(
  '/example.forum_rendering.proto.ForumRenderer/GetNewPostPage',
  grpc.web.MethodType.UNARY,
  proto.example.forum_rendering.proto.EmptyRequest,
  proto.example.forum_rendering.proto.HTMLResponse,
  /**
   * @param {!proto.example.forum_rendering.proto.EmptyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.example.forum_rendering.proto.HTMLResponse.deserializeBinary
);


/**
 * @param {!proto.example.forum_rendering.proto.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.example.forum_rendering.proto.HTMLResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.example.forum_rendering.proto.HTMLResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.example.forum_rendering.proto.ForumRendererClient.prototype.getNewPostPage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/example.forum_rendering.proto.ForumRenderer/GetNewPostPage',
      request,
      metadata || {},
      methodDescriptor_ForumRenderer_GetNewPostPage,
      callback);
};


/**
 * @param {!proto.example.forum_rendering.proto.EmptyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.example.forum_rendering.proto.HTMLResponse>}
 *     Promise that resolves to the response
 */
proto.example.forum_rendering.proto.ForumRendererPromiseClient.prototype.getNewPostPage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/example.forum_rendering.proto.ForumRenderer/GetNewPostPage',
      request,
      metadata || {},
      methodDescriptor_ForumRenderer_GetNewPostPage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.example.forum_rendering.proto.CreatePostRequest,
 *   !proto.example.forum_rendering.proto.HTMLResponse>}
 */
const methodDescriptor_ForumRenderer_CreateNewPost = new grpc.web.MethodDescriptor(
  '/example.forum_rendering.proto.ForumRenderer/CreateNewPost',
  grpc.web.MethodType.UNARY,
  proto.example.forum_rendering.proto.CreatePostRequest,
  proto.example.forum_rendering.proto.HTMLResponse,
  /**
   * @param {!proto.example.forum_rendering.proto.CreatePostRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.example.forum_rendering.proto.HTMLResponse.deserializeBinary
);


/**
 * @param {!proto.example.forum_rendering.proto.CreatePostRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.example.forum_rendering.proto.HTMLResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.example.forum_rendering.proto.HTMLResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.example.forum_rendering.proto.ForumRendererClient.prototype.createNewPost =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/example.forum_rendering.proto.ForumRenderer/CreateNewPost',
      request,
      metadata || {},
      methodDescriptor_ForumRenderer_CreateNewPost,
      callback);
};


/**
 * @param {!proto.example.forum_rendering.proto.CreatePostRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.example.forum_rendering.proto.HTMLResponse>}
 *     Promise that resolves to the response
 */
proto.example.forum_rendering.proto.ForumRendererPromiseClient.prototype.createNewPost =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/example.forum_rendering.proto.ForumRenderer/CreateNewPost',
      request,
      metadata || {},
      methodDescriptor_ForumRenderer_CreateNewPost);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.example.forum_rendering.proto.GetPostRequest,
 *   !proto.example.forum_rendering.proto.HTMLResponse>}
 */
const methodDescriptor_ForumRenderer_GetPost = new grpc.web.MethodDescriptor(
  '/example.forum_rendering.proto.ForumRenderer/GetPost',
  grpc.web.MethodType.UNARY,
  proto.example.forum_rendering.proto.GetPostRequest,
  proto.example.forum_rendering.proto.HTMLResponse,
  /**
   * @param {!proto.example.forum_rendering.proto.GetPostRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.example.forum_rendering.proto.HTMLResponse.deserializeBinary
);


/**
 * @param {!proto.example.forum_rendering.proto.GetPostRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.example.forum_rendering.proto.HTMLResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.example.forum_rendering.proto.HTMLResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.example.forum_rendering.proto.ForumRendererClient.prototype.getPost =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/example.forum_rendering.proto.ForumRenderer/GetPost',
      request,
      metadata || {},
      methodDescriptor_ForumRenderer_GetPost,
      callback);
};


/**
 * @param {!proto.example.forum_rendering.proto.GetPostRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.example.forum_rendering.proto.HTMLResponse>}
 *     Promise that resolves to the response
 */
proto.example.forum_rendering.proto.ForumRendererPromiseClient.prototype.getPost =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/example.forum_rendering.proto.ForumRenderer/GetPost',
      request,
      metadata || {},
      methodDescriptor_ForumRenderer_GetPost);
};


module.exports = proto.example.forum_rendering.proto;

