# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import forum_pb2 as forum__pb2


class ForumRendererStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHomePage = channel.unary_unary(
                '/example.forum_rendering.proto.ForumRenderer/GetHomePage',
                request_serializer=forum__pb2.EmptyRequest.SerializeToString,
                response_deserializer=forum__pb2.HTMLResponse.FromString,
                )
        self.GetNewPostPage = channel.unary_unary(
                '/example.forum_rendering.proto.ForumRenderer/GetNewPostPage',
                request_serializer=forum__pb2.EmptyRequest.SerializeToString,
                response_deserializer=forum__pb2.HTMLResponse.FromString,
                )
        self.CreateNewPost = channel.unary_unary(
                '/example.forum_rendering.proto.ForumRenderer/CreateNewPost',
                request_serializer=forum__pb2.CreatePostRequest.SerializeToString,
                response_deserializer=forum__pb2.HTMLResponse.FromString,
                )
        self.GetPost = channel.unary_unary(
                '/example.forum_rendering.proto.ForumRenderer/GetPost',
                request_serializer=forum__pb2.GetPostRequest.SerializeToString,
                response_deserializer=forum__pb2.HTMLResponse.FromString,
                )


class ForumRendererServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHomePage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNewPostPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNewPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ForumRendererServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHomePage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHomePage,
                    request_deserializer=forum__pb2.EmptyRequest.FromString,
                    response_serializer=forum__pb2.HTMLResponse.SerializeToString,
            ),
            'GetNewPostPage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNewPostPage,
                    request_deserializer=forum__pb2.EmptyRequest.FromString,
                    response_serializer=forum__pb2.HTMLResponse.SerializeToString,
            ),
            'CreateNewPost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNewPost,
                    request_deserializer=forum__pb2.CreatePostRequest.FromString,
                    response_serializer=forum__pb2.HTMLResponse.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=forum__pb2.GetPostRequest.FromString,
                    response_serializer=forum__pb2.HTMLResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.forum_rendering.proto.ForumRenderer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ForumRenderer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHomePage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.forum_rendering.proto.ForumRenderer/GetHomePage',
            forum__pb2.EmptyRequest.SerializeToString,
            forum__pb2.HTMLResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNewPostPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.forum_rendering.proto.ForumRenderer/GetNewPostPage',
            forum__pb2.EmptyRequest.SerializeToString,
            forum__pb2.HTMLResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateNewPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.forum_rendering.proto.ForumRenderer/CreateNewPost',
            forum__pb2.CreatePostRequest.SerializeToString,
            forum__pb2.HTMLResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.forum_rendering.proto.ForumRenderer/GetPost',
            forum__pb2.GetPostRequest.SerializeToString,
            forum__pb2.HTMLResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
